import { isChineseLanguage, useAppPreferencesStore } from "./store";

export const APP_COPY = {
  en: {
    common: {
      yes: "Yes",
      no: "No",
      cancel: "Cancel",
      refresh: "Refresh",
      reload: "Reload",
      save: "Save",
      updated: (relative: string) => `Updated ${relative}`,
      waitingForData: "Waiting for data",
      loading: "Loading…",
      active: "active",
      idle: "idle",
      invalid: "Invalid",
      ready: "Ready",
    },
    status: {
      connected: "Connected",
      connecting: "Connecting",
      authenticating: "Authenticating",
      reconnecting: "Reconnecting",
      pairing_required: "Pairing Required",
      disconnected: "Disconnected",
      error: "Error",
      running: "Running",
      idle: "Idle",
      linked: "Linked",
      notLinked: "Not linked",
    },
    errorBoundary: {
      title: "Something went wrong",
      fallback: "An unexpected error occurred",
      retry: "Try Again",
    },
    connection: {
      title: "Gateway Connection",
      subtitle: "Connect to your OpenClaw Gateway server",
      runtimeDiagnostics: "Runtime Diagnostics",
      runtimeDiagnosticsDetail: "Active Tauri/WebView context and the latest gateway handshake trace.",
      client: "Client",
      webviewOrigin: "WebView origin",
      webviewHref: "WebView href",
      protocol: "Protocol",
      host: "Host",
      baseUri: "Base URI",
      userAgent: "User agent",
      platform: "Platform",
      tauriDetected: "Tauri detected",
      wsOriginHeader: "WS Origin header",
      transport: "Transport",
      handshakeTrace: "Handshake trace",
      noConnectionAttempts: "No connection attempts captured yet.",
      addGateway: "Add Gateway",
      disconnect: "Disconnect",
      connect: "Connect",
      addGatewayConfiguration: "Add Gateway Configuration",
      name: "Name",
      gatewayUrl: "Gateway URL",
      token: "Token",
      gatewayNamePlaceholder: "My Gateway Server",
      gatewayUrlPlaceholder: "wss://your-server:18789",
      gatewayUrlHint: "WebSocket address of your OpenClaw Gateway",
      tokenPlaceholder: "Your Gateway token",
      nameRequired: "Name is required",
      urlRequired: "Valid WebSocket URL required (wss:// or ws://)",
      tokenRequired: "Token is required",
      yes: "yes",
      no: "no",
    },
    channels: {
      title: "Channels",
      subtitle: "Official-style channel workspace with per-channel status, account detail, structured config, enable toggles, probe actions, and WhatsApp / Nostr flows.",
      emptySubtitle: "Connect a gateway to inspect channel health, login state, and channel config panels.",
      eyebrow: "Control Surface",
      deepProbeOn: "Deep Probe On",
      fastStatus: "Fast Status",
      reloadConfig: "Reload Config",
      activeCount: (active: number, total: number) => `${active}/${total} active`,
      accountsCount: (total: number) => `${total} accounts`,
      deepProbe: "deep probe",
      fastMode: "fast status",
      loading: "Loading channels…",
      empty: "No channels reported by the gateway yet.",
      accountCount: (count: number) => `${count} account${count === 1 ? "" : "s"}`,
      defaultAccount: (accountId: string) => `default ${accountId}`,
      linked: "Linked",
      notLinked: "Not linked",
      whatsappQrAlt: "WhatsApp QR code",
      editProfile: "Edit Profile",
      disable: "Disable",
      enable: "Enable",
      showQr: "Show QR",
      relink: "Relink",
      wait: "Wait",
      logout: "Logout",
      probe: "Probe",
      configuration: "Configuration",
      gatewayConfig: "Gateway config",
      channelHealth: "Channel Health",
      channelHealthDetail: "Raw `channels.status` snapshot from the gateway for parity checks and diagnostics.",
      deepProbeLabel: "Deep probe",
      fastModeLabel: "Fast mode",
      configured: "Configured",
      running: "Running",
      connected: "Connected",
      lastInbound: "Last inbound",
      lastProbe: "Last probe",
      publicKey: "Public Key",
      flags: "Flags",
      profile: "Profile",
      name: "Name",
      display: "Display",
      website: "Website",
      noProfilePublished: "No profile published.",
      accountFallback: (index: number) => `Account ${index + 1}`,
    },
    nostrProfile: {
      title: "Nostr Profile",
      subtitle: (accountId: string) => `Publish a kind:0 profile for account \`${accountId}\`.`,
      accountMeta: (accountId: string) => `account ${accountId}`,
      unsaved: "unsaved",
      synced: "synced",
      previewAlt: "Nostr profile preview",
      username: "Username",
      usernameHelp: "Short profile name.",
      displayName: "Display Name",
      displayNameHelp: "Name shown to other clients.",
      avatarUrl: "Avatar URL",
      avatarUrlHelp: "HTTPS image URL.",
      bio: "Bio",
      bioHelp: "Free-form profile description.",
      bioPlaceholder: "Tell people about this relay identity...",
      bannerUrl: "Banner URL",
      website: "Website",
      nip05: "NIP-05",
      lud16: "LUD-16",
      saveAndPublish: "Save & Publish",
      import: "Import",
      hideAdvanced: "Hide Advanced",
      showAdvanced: "Show Advanced",
      cancel: "Cancel",
    },
  },
  zh: {
    common: {
      yes: "是",
      no: "否",
      cancel: "取消",
      refresh: "刷新",
      reload: "重新加载",
      save: "保存",
      updated: (relative: string) => `更新于${relative}`,
      waitingForData: "等待数据",
      loading: "加载中…",
      active: "活跃",
      idle: "空闲",
      invalid: "无效",
      ready: "就绪",
    },
    status: {
      connected: "已连接",
      connecting: "连接中",
      authenticating: "认证中",
      reconnecting: "重连中",
      pairing_required: "等待配对",
      disconnected: "未连接",
      error: "错误",
      running: "运行中",
      idle: "空闲",
      linked: "已绑定",
      notLinked: "未绑定",
    },
    errorBoundary: {
      title: "页面出错了",
      fallback: "发生了未预期的错误",
      retry: "重试",
    },
    connection: {
      title: "网关连接",
      subtitle: "连接到你的 OpenClaw Gateway 服务",
      runtimeDiagnostics: "运行时诊断",
      runtimeDiagnosticsDetail: "展示当前 Tauri/WebView 环境以及最近一次网关握手轨迹。",
      client: "客户端",
      webviewOrigin: "WebView 来源",
      webviewHref: "WebView 地址",
      protocol: "协议",
      host: "主机",
      baseUri: "基础 URI",
      userAgent: "用户代理",
      platform: "平台",
      tauriDetected: "检测到 Tauri",
      wsOriginHeader: "WS Origin 头",
      transport: "传输层",
      handshakeTrace: "握手轨迹",
      noConnectionAttempts: "暂时还没有捕获到连接尝试。",
      addGateway: "添加网关",
      disconnect: "断开连接",
      connect: "连接",
      addGatewayConfiguration: "添加网关配置",
      name: "名称",
      gatewayUrl: "网关地址",
      token: "令牌",
      gatewayNamePlaceholder: "我的网关服务",
      gatewayUrlPlaceholder: "wss://你的服务:18789",
      gatewayUrlHint: "你的 OpenClaw Gateway WebSocket 地址",
      tokenPlaceholder: "你的网关令牌",
      nameRequired: "名称不能为空",
      urlRequired: "请输入有效的 WebSocket 地址（wss:// 或 ws://）",
      tokenRequired: "令牌不能为空",
      yes: "是",
      no: "否",
    },
    channels: {
      title: "渠道",
      subtitle: "官方风格的渠道工作区，包含每个渠道的状态、账号详情、结构化配置、启停开关、探测动作以及 WhatsApp / Nostr 流程。",
      emptySubtitle: "先连接网关，再查看渠道健康状态、登录状态和渠道配置面板。",
      eyebrow: "控制台",
      deepProbeOn: "深度探测",
      fastStatus: "快速状态",
      reloadConfig: "重载配置",
      activeCount: (active: number, total: number) => `${active}/${total} 已启用`,
      accountsCount: (total: number) => `${total} 个账号`,
      deepProbe: "深度探测",
      fastMode: "快速状态",
      loading: "正在加载渠道…",
      empty: "网关暂时还没有上报任何渠道。",
      accountCount: (count: number) => `${count} 个账号`,
      defaultAccount: (accountId: string) => `默认 ${accountId}`,
      linked: "已绑定",
      notLinked: "未绑定",
      whatsappQrAlt: "WhatsApp 二维码",
      editProfile: "编辑资料",
      disable: "停用",
      enable: "启用",
      showQr: "显示二维码",
      relink: "重新绑定",
      wait: "等待",
      logout: "退出登录",
      probe: "探测",
      configuration: "配置",
      gatewayConfig: "网关配置",
      channelHealth: "渠道健康状态",
      channelHealthDetail: "来自网关的原始 `channels.status` 快照，用于对齐和诊断。",
      deepProbeLabel: "深度探测",
      fastModeLabel: "快速模式",
      configured: "已配置",
      running: "运行中",
      connected: "已连接",
      lastInbound: "最近入站",
      lastProbe: "最近探测",
      publicKey: "公钥",
      flags: "标记",
      profile: "资料",
      name: "名称",
      display: "显示名",
      website: "网站",
      noProfilePublished: "还没有发布资料。",
      accountFallback: (index: number) => `账号 ${index + 1}`,
    },
    nostrProfile: {
      title: "Nostr 资料",
      subtitle: (accountId: string) => `为账号 \`${accountId}\` 发布 kind:0 资料。`,
      accountMeta: (accountId: string) => `账号 ${accountId}`,
      unsaved: "未保存",
      synced: "已同步",
      previewAlt: "Nostr 资料预览",
      username: "用户名",
      usernameHelp: "简短的资料名称。",
      displayName: "显示名",
      displayNameHelp: "展示给其他客户端的名称。",
      avatarUrl: "头像地址",
      avatarUrlHelp: "HTTPS 图片地址。",
      bio: "简介",
      bioHelp: "自由填写的资料说明。",
      bioPlaceholder: "介绍一下这个 relay 身份…",
      bannerUrl: "横幅地址",
      website: "网站",
      nip05: "NIP-05",
      lud16: "LUD-16",
      saveAndPublish: "保存并发布",
      import: "导入",
      hideAdvanced: "收起高级项",
      showAdvanced: "显示高级项",
      cancel: "取消",
    },
  },
} as const;

export function getAppCopy() {
  const language = useAppPreferencesStore.getState().language;
  return isChineseLanguage(language) ? APP_COPY.zh : APP_COPY.en;
}
