import { isChineseLanguage } from "@/features/preferences/store";

const EN_OVERVIEW_COPY = {
  na: "n/a",
  zeroSeconds: "0s",
  modelUnspecified: "Unspecified model",
  providerUnknown: "unknown",
  unassignedAgent: "unassigned agent",
  noAgent: "no agent",
  liveStatusProbe: "Live status probe",
  desktopWs: "Desktop WS",
  webSocket: "WebSocket",
  trustedProxy: "trusted-proxy",
  tokenPassword: "token/password",
  connectionStates: {
    online: "Online",
    connecting: "Connecting",
    authenticating: "Authenticating",
    pairingRequired: "Pairing required",
    error: "Error",
    reconnecting: "Reconnecting",
    offline: "Offline",
  },
  healthLabels: {
    ok: "Healthy",
    danger: "Degraded",
    warn: "Checking",
    info: "Unknown",
  },
  hero: {
    eyebrow: "Control Surface",
    title: "Overview",
    subtitle: "Official-style gateway command center with live health, usage, alerts, and quick actions.",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    waitingForData: "Waiting for data",
    updated: (relative: string) => `Updated ${relative}`,
  },
  access: {
    title: "Gateway Access",
    subtitle: "Same connection surface as the official WebUI, with desktop-friendly profile switching.",
    profile: "Profile",
    noSavedProfiles: "No saved profiles",
    switchConfig: "Switch Config",
    websocketUrl: "WebSocket URL",
    gatewayToken: "Gateway Token",
    password: "Password (not stored)",
    passwordPlaceholder: "system or shared password",
    defaultSessionKey: "Default Session Key",
    language: "Language",
    connect: "Connect",
    connecting: "Connecting…",
    newSession: "New Session",
    trustedProxyHint: "Authenticated via trusted proxy.",
    sessionHint: "Apply URL or token changes from here, then jump straight into a new session.",
  },
  snapshot: {
    title: "System Snapshot",
    subtitle: "Gateway, connection, and health at a glance, aligned with upstream overview semantics.",
    gateway: "Gateway",
    connection: "Connection",
    health: "Health",
    uptime: "Uptime",
    tickInterval: "Tick Interval",
    lastHeartbeat: "Last Heartbeat",
    channelsRefresh: "Channels Refresh",
  },
  metrics: {
    activeSessions: "Active Sessions",
    activeSessionsDetail: "Recent session keys tracked by the gateway.",
    presenceBeacons: "Presence Beacons",
    presenceBeaconsDetail: "Instances seen in the latest presence snapshot.",
    sevenDayTokens: "7-Day Tokens",
    messagesInWindow: (countText: string) => `${countText} messages in the current usage window.`,
    usageCost: "Usage Cost",
    usageCostDetail: "Input, output, cache read, and cache write blended cost.",
    modelCoverage: "Model Coverage",
    modelCoverageDetail: (countText: string) => `${countText} catalog models returned by \`models.list\`.`,
    channelsOnline: "Channels Online",
    cronSummary: (state: string, nextRun: string) => `Cron ${state} · next run ${nextRun}`,
    cronEnabled: "enabled",
    cronDisabled: "disabled",
  },
  usage: {
    title: "Token Usage",
    subtitle: "Seven-day token and cost trend, optimized for low-jank refreshes.",
    messages: "Messages",
    cost: "Cost",
    cacheRead: "Cache Read",
  },
  models: {
    title: "Model Distribution",
    subtitle: "Top models by token share in the same usage window.",
    providersCount: (count: number) => `${count} providers`,
    empty: "No model usage has been reported for the current window yet.",
    tokensAndRuns: (tokens: string, runs: string) => `${tokens} tokens · ${runs} runs`,
  },
  quickActions: {
    title: "Quick Actions",
    subtitle: "One-click entry points for the most common operator flows.",
    newSession: "New Session",
    newSessionDetail: "Open chat with a fresh draft conversation.",
    switchConfig: "Switch Config",
    switchConfigDetail: "Reconnect using the selected gateway profile.",
    viewLogs: "View Logs",
    viewLogsDetail: "Inspect recent gateway events buffered locally.",
    openConfig: "Open Config",
    openConfigDetail: "Jump to raw gateway config and auth metadata.",
    noProfiles: "No saved gateway profiles yet. Add one from this page or the connection workspace.",
  },
  notifications: {
    title: "Alerts & Notifications",
    subtitle: "Warnings, auth hints, and operational reminders surfaced from live diagnostics.",
    activeCount: (count: number) => `${count} active`,
    empty: "No active alerts. Gateway health, auth, and usage signals look stable.",
  },
  timeline: {
    title: "Recent Activity",
    subtitle: "Merged timeline of recent sessions, gateway events, and heartbeat diagnostics.",
    itemCount: (count: number) => `${count} items`,
    empty: "No recent activity yet. Connect a gateway and start a session to populate the timeline.",
    sessionDetail: (messageCount: string, agent: string) => `${messageCount} messages · ${agent}`,
    heartbeatReceived: "Heartbeat received",
    heartbeatDetail: "Gateway heartbeat updated the local client diagnostics.",
  },
  notes: {
    title: "Runtime Notes",
    subtitle: "Official-style operator reminders plus live desktop diagnostics.",
    tailscaleTitle: "Tailscale serve",
    tailscaleDetail: "Prefer Tailscale Serve to keep the gateway on loopback while preserving device auth and safer exposure.",
    sessionTitle: "Session hygiene",
    sessionDetail: "Use a fresh draft session for context resets, or jump to Sessions to patch metadata and defaults.",
    cronTitle: "Cron reminders",
    cronDetail: "Keep recurring tasks isolated from ad-hoc operator chats to preserve deterministic prompts and token accounting.",
    runtime: "Runtime",
    transport: "Transport",
    authSurface: "Auth surface",
    methodsEvents: "Methods / Events",
  },
  alerts: {
    gatewayConnectionIssue: "Gateway connection issue",
    pairingRequired: "Pairing required",
    authenticationRequired: "Authentication required",
    authenticationRequiredDetail: "Provide a valid gateway token or trusted proxy session, then reconnect.",
    healthChecksDegraded: "Health checks degraded",
    healthChecksDegradedDetail: "The latest status/health snapshot indicates the gateway may not be serving requests cleanly.",
    partialDataRefresh: "Partial data refresh",
    partialDataRefreshDetail: (count: number) => `${count} overview RPC calls failed, so some cards may be stale until the next refresh.`,
    tokenNotStored: "Token not stored",
    tokenNotStoredDetail: "This profile has no persisted token. Reconnect from a tokenized URL to streamline future access.",
    noModelsCatalog: "No models catalog reported",
    noModelsCatalogDetail: "`models.list` returned empty. Verify providers are configured and reachable.",
    cronDisabled: "Cron is disabled",
    cronDisabledDetail: "Scheduled automations are paused. Re-enable cron if you expect recurring tasks to run.",
  },
  callouts: {
    pairingNeedApproval: "This device needs pairing approval from the gateway host.",
    devicePairingDocs: "Docs: Device pairing",
    authRequired: "The gateway requires authentication. Add a token or trusted proxy session, then reconnect.",
    authFailed: "Auth failed. Re-copy a tokenized URL with openclaw dashboard --no-open, or update the token, then click Connect.",
    authDocs: "Docs: Control UI auth",
    insecureHttp: "This page is HTTP, so the browser blocks device identity. Use HTTPS through Tailscale Serve, or open http://127.0.0.1:18789 on the gateway host.",
    insecureHttpDetail: "If you must stay on HTTP, set gateway.controlUi.allowInsecureAuth: true (token-only).",
    tailscaleDocs: "Docs: Tailscale Serve",
    insecureHttpDocs: "Docs: Insecure HTTP",
    partialRpc: "Some overview RPCs failed to refresh, so a few panels may still be stale while the dashboard keeps the last good snapshot visible.",
    channelsHint: "Use Channels to link WhatsApp, Telegram, Discord, Signal, or iMessage and keep their health visible here.",
  },
  sessionList: {
    title: (title: string, messageCount: string) => `${title} · ${messageCount} messages`,
    meta: (agent: string, messageCount: string) => `${agent} · ${messageCount} messages`,
  },
  chart: {
    tooltip: (label: string, tokens: string, cost: string) => `${label}: ${tokens} tokens · ${cost}`,
  },
} as const;

export type OverviewCopy = typeof EN_OVERVIEW_COPY;

const ZH_OVERVIEW_COPY: OverviewCopy = {
  na: "暂无",
  zeroSeconds: "0秒",
  modelUnspecified: "未指定模型",
  providerUnknown: "未知",
  unassignedAgent: "未分配 Agent",
  noAgent: "无 Agent",
  liveStatusProbe: "实时状态探测",
  desktopWs: "桌面 WS",
  webSocket: "WebSocket",
  trustedProxy: "trusted-proxy",
  tokenPassword: "token/password",
  connectionStates: {
    online: "在线",
    connecting: "连接中",
    authenticating: "认证中",
    pairingRequired: "等待配对",
    error: "错误",
    reconnecting: "重连中",
    offline: "离线",
  },
  healthLabels: {
    ok: "健康",
    danger: "异常",
    warn: "检查中",
    info: "未知",
  },
  hero: {
    eyebrow: "控制台",
    title: "概览",
    subtitle: "官方风格的网关总览中心，集中展示健康状态、用量、告警与快捷操作。",
    refresh: "刷新",
    refreshing: "刷新中…",
    waitingForData: "等待数据",
    updated: (relative: string) => `更新于${relative}`,
  },
  access: {
    title: "网关接入",
    subtitle: "与官方 WebUI 一致的连接界面，并补充更适合桌面端的配置切换。",
    profile: "配置",
    noSavedProfiles: "暂无已保存配置",
    switchConfig: "切换配置",
    websocketUrl: "WebSocket 地址",
    gatewayToken: "网关令牌",
    password: "密码（不保存）",
    passwordPlaceholder: "系统密码或共享密码",
    defaultSessionKey: "默认会话 Key",
    language: "语言",
    connect: "连接",
    connecting: "连接中…",
    newSession: "新建会话",
    trustedProxyHint: "当前通过受信代理认证。",
    sessionHint: "可以在这里更新地址或令牌，然后直接跳转到新会话。",
  },
  snapshot: {
    title: "系统快照",
    subtitle: "一眼查看网关、连接与健康状态，并与官方概览语义保持一致。",
    gateway: "网关",
    connection: "连接",
    health: "健康",
    uptime: "运行时长",
    tickInterval: "轮询间隔",
    lastHeartbeat: "最近心跳",
    channelsRefresh: "渠道刷新",
  },
  metrics: {
    activeSessions: "活跃会话",
    activeSessionsDetail: "网关近期跟踪到的会话键。",
    presenceBeacons: "在线信标",
    presenceBeaconsDetail: "最近一次在线快照中发现的实例数。",
    sevenDayTokens: "7 日 Tokens",
    messagesInWindow: (countText: string) => `当前统计窗口内共 ${countText} 条消息。`,
    usageCost: "使用成本",
    usageCostDetail: "综合输入、输出、缓存读取与缓存写入后的成本。",
    modelCoverage: "模型覆盖",
    modelCoverageDetail: (countText: string) => `\`models.list\` 返回了 ${countText} 个目录模型。`,
    channelsOnline: "在线渠道",
    cronSummary: (state: string, nextRun: string) => `Cron ${state} · 下次执行 ${nextRun}`,
    cronEnabled: "已启用",
    cronDisabled: "已停用",
  },
  usage: {
    title: "Token 用量",
    subtitle: "展示最近 7 天的 Token 与成本趋势，并针对低抖动刷新做了优化。",
    messages: "消息数",
    cost: "成本",
    cacheRead: "缓存读取",
  },
  models: {
    title: "模型分布",
    subtitle: "当前统计窗口内按 Token 占比排序的模型。",
    providersCount: (count: number) => `${count} 个提供商`,
    empty: "当前统计窗口还没有模型使用数据。",
    tokensAndRuns: (tokens: string, runs: string) => `${tokens} Tokens · ${runs} 次运行`,
  },
  quickActions: {
    title: "快捷操作",
    subtitle: "一键进入最常见的运维操作路径。",
    newSession: "新建会话",
    newSessionDetail: "打开聊天页并创建一条新的草稿会话。",
    switchConfig: "切换配置",
    switchConfigDetail: "使用当前选中的网关配置重新连接。",
    viewLogs: "查看日志",
    viewLogsDetail: "检查本地缓冲的最近网关事件。",
    openConfig: "打开配置",
    openConfigDetail: "跳转到原始网关配置和认证元数据。",
    noProfiles: "还没有已保存的网关配置。可以在本页或连接工作区中添加。",
  },
  notifications: {
    title: "告警与通知",
    subtitle: "根据实时诊断结果展示警告、认证提示和运行提醒。",
    activeCount: (count: number) => `${count} 条激活中`,
    empty: "当前没有活动告警。网关健康、认证和用量信号都比较稳定。",
  },
  timeline: {
    title: "最近活动",
    subtitle: "整合最近会话、网关事件和心跳诊断的时间线。",
    itemCount: (count: number) => `${count} 条记录`,
    empty: "暂时没有最近活动。先连接网关并发起会话，这里就会出现时间线。",
    sessionDetail: (messageCount: string, agent: string) => `${messageCount} 条消息 · ${agent}`,
    heartbeatReceived: "收到心跳",
    heartbeatDetail: "网关心跳已更新本地客户端诊断信息。",
  },
  notes: {
    title: "运行说明",
    subtitle: "官方风格的操作提醒，外加桌面端实时诊断信息。",
    tailscaleTitle: "Tailscale Serve",
    tailscaleDetail: "优先使用 Tailscale Serve，把网关保留在本地回环地址，同时保住设备认证与更安全的暴露方式。",
    sessionTitle: "会话卫生",
    sessionDetail: "需要重置上下文时，请使用新的草稿会话；也可以去 Sessions 页面修补元数据和默认值。",
    cronTitle: "Cron 提醒",
    cronDetail: "把定时任务和临时运维聊天隔离开，能更好地保持提示词和 Token 统计的确定性。",
    runtime: "运行时",
    transport: "传输层",
    authSurface: "认证面",
    methodsEvents: "方法 / 事件",
  },
  alerts: {
    gatewayConnectionIssue: "网关连接异常",
    pairingRequired: "需要配对",
    authenticationRequired: "需要认证",
    authenticationRequiredDetail: "请提供有效的网关令牌或受信代理会话后重新连接。",
    healthChecksDegraded: "健康检查异常",
    healthChecksDegradedDetail: "最新的状态/健康快照表明，网关当前可能无法稳定处理请求。",
    partialDataRefresh: "数据部分刷新失败",
    partialDataRefreshDetail: (count: number) => `${count} 个 overview RPC 调用失败，因此部分卡片可能会在下次刷新前保持旧数据。`,
    tokenNotStored: "令牌未保存",
    tokenNotStoredDetail: "当前配置没有持久化令牌。请用带令牌的 URL 重新连接，以便后续访问更顺畅。",
    noModelsCatalog: "未返回模型目录",
    noModelsCatalogDetail: "`models.list` 返回为空，请检查提供商是否已正确配置且可访问。",
    cronDisabled: "Cron 已停用",
    cronDisabledDetail: "计划任务当前处于暂停状态。如果你预期定期任务会运行，请重新启用 Cron。",
  },
  callouts: {
    pairingNeedApproval: "当前设备需要网关宿主机批准配对请求。",
    devicePairingDocs: "文档：设备配对",
    authRequired: "网关要求认证。请补充令牌或受信代理会话后重新连接。",
    authFailed: "认证失败。请重新复制带令牌的 URL（`openclaw dashboard --no-open`），或更新令牌后再点击连接。",
    authDocs: "文档：控制界面认证",
    insecureHttp: "当前页面通过 HTTP 打开，因此浏览器会拦截设备身份认证。请通过 Tailscale Serve 使用 HTTPS，或在网关宿主机上打开 http://127.0.0.1:18789。",
    insecureHttpDetail: "如果必须继续使用 HTTP，请设置 gateway.controlUi.allowInsecureAuth: true（仅令牌模式）。",
    tailscaleDocs: "文档：Tailscale Serve",
    insecureHttpDocs: "文档：不安全 HTTP",
    partialRpc: "部分 overview RPC 刷新失败，因此少数面板可能仍显示旧快照，但仪表盘会继续保留最后一次成功数据。",
    channelsHint: "可以通过 Channels 连接 WhatsApp、Telegram、Discord、Signal 或 iMessage，并在这里持续查看它们的健康状态。",
  },
  sessionList: {
    title: (title: string, messageCount: string) => `${title} · ${messageCount} 条消息`,
    meta: (agent: string, messageCount: string) => `${agent} · ${messageCount} 条消息`,
  },
  chart: {
    tooltip: (label: string, tokens: string, cost: string) => `${label}：${tokens} Tokens · ${cost}`,
  },
};

export function getOverviewCopy(language: string): OverviewCopy {
  return isChineseLanguage(language) ? ZH_OVERVIEW_COPY : EN_OVERVIEW_COPY;
}
